;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-delete-char
        cf-kill
        evil-change
        evil-next-line
        evil-normal-state
        org-self-insert-command
        org-yank
        paredit-backslash
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        ))
